name: Detect Issue Movement in Any GitHub Project

on:
  project_card:
    types:
      - moved

jobs:
  detectMovement:
    runs-on: ubuntu-latest

    steps:
      - name: Print event data
        run: |
          echo "GitHub Event Data: ${{ toJson(github.event) }}"
