name: Trigger Action on specific comment

on:
  issue_comment:
    types:
      - created  # El action se activa cuando se crea un comentario en un issue.

jobs:
  check_movement_comment:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the comment matches the movement pattern
        run: |
          COMMENT_BODY="${{ github.event.comment.body }}"
          echo "New comment on issue: $COMMENT_BODY"
          
          # Verificar si el comentario contiene el texto específico "moved this from"
          if [[ "$COMMENT_BODY" == *"moved this from"* ]]; then
            echo "Movement detected in comment"
            
            # Aquí puedes ejecutar cualquier acción que necesites, como enviar el comentario a un servicio.
            curl -X POST "https://script.google.com/macros/s/AKfycbxhApYr834vi421taQw6mH8eS0Nl8tWmVxOI_KB6da7L_gN80yNlo0BorscDAOnT1y0/exec" \
              -H "Content-Type: application/json" \
              -d '{"repoName": "${{ github.repository }}", "issue": {"title": "${{ github.event.issue.title }}", "url": "${{ github.event.issue.html_url }}", "comment": "'$COMMENT_BODY'"}}'
          else
            echo "No movement detected"
          fi
