name: Detectar Labeled en Issues

on:
  issues:
    types: [labeled]  # Este evento se dispara cuando un label es asignado a un issue

jobs:
  show_label_info:
    runs-on: ubuntu-latest  # El runner en el que se ejecutará el job
    
    steps:
    - name: Mostrar información del label
      run: |
        echo "Se ha etiquetado un issue"
        echo "Número de Issue: ${{ github.event.issue.number }}"
        echo "Título del Issue: ${{ github.event.issue.title }}"
        echo "Etiqueta aplicada: ${{ github.event.label.name }}"