name: Create Google Sheet for New Repo

on:
  push:
    branches:
      - main  # Esto se ejecutará cuando se haga push en la rama principal

jobs:
  notify_google_script:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Google Apps Script
        env:
          # GOOGLE_SCRIPT_URL: ${{ secrets.GOOGLE_SCRIPT_URL }}  # Comentada
          GOOGLE_SCRIPT_URL: 'https://script.google.com/a/macros/didcom.com.mx/s/AKfycbzXjxxQfmjHZDSdh3d18TTEY1XNgHnm7HnLN3oUbhyw0ktTLSL4wJAFQyiU0t7ayjjy/exec'  # URL de tu script          
          #la url sera un secret a nivel organizacion
          REPO_NAME: ${{ github.repository }}
        
        run: |
          curl -X POST "$GOOGLE_SCRIPT_URL" \
          -H "Content-Type: application/json" \
          -d "{\"repoName\": \"$REPO_NAME\"}"