name: Create Google Sheet for New Repo

on:
  push:
    branches:
      - main  # Esto se ejecutará cuando se haga push en la rama principal

jobs:
  notify_google_script:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Google Apps Script
        env:
          GOOGLE_SCRIPT_URL: ${{ secrets.GOOGLE_SCRIPT_URL_ENDPOINT_CREATE_BACKLOG_FILE }}
          REPO_NAME: ${{ github.repository }}
        
        run: |
          curl -X POST "$GOOGLE_SCRIPT_URL" \
          -H "Content-Type: application/json" \
          -d "{\"repoName\": \"$REPO_NAME\"}"