# ------------------------------------------------------------
# Workflow: Sync GitHub Issues with Jira
# Autor: Ing. Jesús Jashimoto
# Fecha: 10 de enero de 2025
# Descripción:
#   Este workflow sincroniza los issues creados en GitHub con Jira.
# ------------------------------------------------------------

  name: Sync GitHub Issues with Jira

  on:
    issues:
      types: [opened]
  
  env:
    SYNC_ISSUE_NUMBER: 21 # Número del Issue de Sincronización, puedes modificarlo manualmente
  
  jobs:
    sync-issue:
      runs-on: ubuntu-latest
   
      steps:
  
        # 1. Crear Tarea en Jira
        - name: Crear Tarea en Jira
          id: create-jira-task
          run: |
            echo "Creando tarea en Jira..."
            due_date=$(date -d "+1 month" "+%Y-%m-%d")
            jira_response=$(curl -s -X POST \
            -H "Authorization: Basic ${{ secrets.JIRA_API_AUTH }}" \
            -H "Content-Type: application/json" \
              -d '{
                "fields": {
                  "project": {
                    "key": "CDP"
                  },
                  "summary": "${{ github.event.issue.title }}",
                  "issuetype": {
                    "name": "Task"
                  },
                  "components": [
                    {
                      "name": "Firmware"
                    },
                    {
                      "name": "Sin Asignar"
                    }
                  ],
                  "duedate": "'"$due_date"'"
                }
              }' \
              ${{ secrets.JIRA_URL }}/rest/api/2/issue)
            echo "Respuesta de Jira: $jira_response"
            jira_key=$(echo "$jira_response" | jq -r '.key')
            if [[ -z "$jira_key" || "$jira_key" == "null" ]]; then
              echo "Error: No se pudo crear la tarea en Jira. Revisa los logs."
              exit 1
            fi
            echo "Tarea en Jira creada con éxito. Key: $jira_key"
            echo "jira_key=$jira_key" >> $GITHUB_ENV
  
        # 2. Agregar etiqueta jira-key al Issue en GitHub
        - name: Agregar etiqueta al Issue en GitHub
          run: |
            echo "Agregando etiqueta jira-key al Issue en GitHub..."
            curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            -d '{
              "labels": ["jira-$GITHUB_ENV:jira_key"]
            }' \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels
            echo "Etiqueta agregada con éxito."
  
        # 3. Enviar enlace del Issue de GitHub a la tarea en Jira
        - name: Enviar enlace del Issue de GitHub a Jira
          run: |
            echo "Agregando enlace del Issue en GitHub a la Tarea en Jira..."
            response=$(curl -s -X POST \
              -H "Authorization: Basic ${{ secrets.JIRA_API_AUTH }}" \
              -H "Content-Type: application/json" \
              -d '{
                "object": {
                  "url": "${{ github.event.issue.html_url }}",
                  "title": "${{ github.event.issue.title }}"
                }
              }' \
              ${{ secrets.JIRA_URL }}/rest/api/2/issue/${{ env.jira_key }}/remotelink)
            echo "Respuesta al enviar el enlace: $response"
            if [[ "$response" == *"error"* ]]; then
              echo "Error al agregar el enlace del Issue en GitHub a la Tarea en Jira. Revisa los logs."
              exit 1
            fi
            echo "Enlace agregado con éxito a la Tarea en Jira."
  