# ------------------------------------------------------------
# Workflow: Sync GitHub Issues with Jira
# Autor: Ing. Jesús Jashimoto
# Fecha: 10 de enero de 2025
# Descripción:
#   Este workflow sincroniza los issues creados en GitHub con Jira.
# ------------------------------------------------------------

  name: Sync GitHub Issues with Jira

  on:
    issues:
      types: [opened]
  
  env:
    SYNC_ISSUE_NUMBER: 21 # Número del Issue de Sincronización, puedes modificarlo manualmente
  
  permissions:
    issues: write       # Permite escribir en los issues (para agregar etiquetas)
    contents: read      # Permite leer contenido del repositorio
  
  jobs:
    sync-issue:
      runs-on: ubuntu-latest
   
      steps:
  
        # 1. Verificar si el Issue ya tiene un label jira-key
        - name: Verificar si el Issue ya tiene un label jira-key
          id: check-label
          run: |
            echo "Verificando etiquetas en el Issue..."
            labels=$(curl -s -H "Authorization: Bearer ${{ secrets.ISSUE_TOKEN }}" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} | jq -r '.labels[].name')
  
            echo "Etiquetas encontradas: $labels"
  
            if echo "$labels" | grep -q "^jira-"; then
              echo "El Issue ya tiene una etiqueta jira-key. No se creará una nueva tarea en Jira."
              raw_jira_key=$(echo "$labels" | grep -o 'jira-[^ ]*')
              jira_key=${raw_jira_key#jira-}
              echo "jira_key=$jira_key" >> $GITHUB_ENV
              echo "label_exists=true" >> $GITHUB_ENV
            else
              echo "No se encontró ninguna etiqueta jira-key. Continuando con la creación de la tarea en Jira."
              echo "label_exists=false" >> $GITHUB_ENV
            fi
  
        # 2. Crear Tarea en Jira
        - name: Crear Tarea en Jira
          if: env.label_exists == 'false'
          id: create-jira-task
          run: |
            echo "Creando tarea en Jira..."
            due_date=$(date -d "+1 month" "+%Y-%m-%d")
            jira_response=$(curl -s -X POST \
            -H "Authorization: Basic ${{ secrets.JIRA_API_AUTH }}" \
            -H "Content-Type: application/json" \
              -d '{
                "fields": {
                  "project": {
                    "key": "CDP"
                  },
                  "summary": "${{ github.event.issue.title }}",
                  "issuetype": {
                    "name": "Task"
                  },
                  "components": [
                    {
                      "name": "Firmware"
                    },
                    {
                      "name": "Sin Asignar"
                    }
                  ],
                  "duedate": "'"$due_date"'"
                }
              }' \
              ${{ secrets.JIRA_URL }}/rest/api/2/issue)
            echo "Respuesta de Jira: $jira_response"
            jira_key=$(echo "$jira_response" | jq -r '.key')
            if [[ -z "$jira_key" || "$jira_key" == "null" ]]; then
              echo "Error: No se pudo crear la tarea en Jira. Revisa los logs."
              exit 1
            fi
            echo "Tarea en Jira creada con éxito. Key: $jira_key"
            echo "jira_key=$jira_key" >> $GITHUB_ENV
  
        # 3. Agregar etiqueta jira-key al Issue en GitHub
        - name: Agregar etiqueta al Issue en GitHub
          if: env.label_exists == 'false'
          run: |
            echo "Agregando etiqueta jira-key al Issue en GitHub..."
            curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.ISSUE_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -d '{
               "labels": ["jira-${{ env.jira_key }}"]
            }' \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels
            echo "Etiqueta agregada con éxito."
  
        # 4. Enviar enlace del Issue de GitHub a la tarea en Jira
        - name: Enviar enlace del Issue de GitHub a Jira
          run: |
            echo "Agregando enlace del Issue en GitHub a la Tarea en Jira..."
            response=$(curl -s -X POST \
              -H "Authorization: Basic ${{ secrets.JIRA_API_AUTH }}" \
              -H "Content-Type: application/json" \
              -d '{
                "object": {
                  "url": "${{ github.event.issue.html_url }}",
                  "title": "${{ github.event.issue.title }}"
                }
              }' \
              ${{ secrets.JIRA_URL }}/rest/api/2/issue/${{ env.jira_key }}/remotelink)
            echo "Respuesta al enviar el enlace: $response"
            if [[ "$response" == *"error"* ]]; then
              echo "Error al agregar el enlace del Issue en GitHub a la Tarea en Jira. Revisa los logs."
              exit 1
            fi
            echo "Enlace agregado con éxito a la Tarea en Jira."
  