name: Insertar tarea en Jira

on:
  issues:
    types: [opened]

jobs:
  create-jira-task:
    runs-on: ubuntu-latest

    steps:
      # 1. Verificar configuración de secrets
      - name: Verificar configuración de secrets
        run: |
          if [[ -z "${{ secrets.JIRA_USERNAME }}" || -z "${{ secrets.JIRA_API_TOKEN }}" || -z "${{ secrets.JIRA_URL }}" ]]; then
            echo "Error: Faltan configuraciones en los secrets (JIRA_USERNAME, JIRA_API_TOKEN, JIRA_URL)."
            exit 1
          fi
          echo "Secrets configurados correctamente."

      # 2. Mostrar configuración de la petición
      - name: Preparar información de la tarea en Jira
        run: |
          due_date=$(date -d "+1 month" "+%Y-%m-%d")

          # Construir el body de la petición
          request_body=$(cat <<EOF
{
  "fields": {
    "project": {
      "key": "CDP"
    },
    "summary": "${{ github.event.issue.title }}",
    "issuetype": {
      "name": "Task"
    },
    "components": [
      {
        "name": "Firmware"
      },
      {
        "name": "Sin Asignar"
      }
    ],
    "duedate": "$due_date"
  }
}
EOF
          )

          # Mostrar información completa de la petición
          echo "=== Información de la petición ==="
          echo "URL: ${{ secrets.JIRA_URL }}/rest/api/3/issue"
          echo "Headers:"
          echo "  Authorization: Basic $(echo -n '${{ secrets.JIRA_USERNAME }}:${{ secrets.JIRA_API_TOKEN }}' | base64)"
          echo "  Content-Type: application/json"
          echo "Body:"
          echo "$request_body"

      # 3. Realizar la petición a Jira
      - name: Insertar tarea en Jira
        run: |
          due_date=$(date -d "+1 month" "+%Y-%m-%d")

          # Construir el body de la petición
          request_body=$(cat <<EOF
{
  "fields": {
    "project": {
      "key": "CDP"
    },
    "summary": "${{ github.event.issue.title }}",
    "issuetype": {
      "name": "Task"
    },
    "components": [
      {
        "name": "Firmware"
      },
      {
        "name": "Sin Asignar"
      }
    ],
    "duedate": "$due_date"
  }
}
EOF
          )

          # Enviar la petición
          jira_response=$(curl -s -X POST \
            -H "Authorization: Basic $(echo -n "${{ secrets.JIRA_USERNAME }}:${{ secrets.JIRA_API_TOKEN }}" | base64)" \
            -H "Content-Type: application/json" \
            -d "$request_body" \
            "${{ secrets.JIRA_URL }}/rest/api/3/issue")

          # Verificar la respuesta
          echo "=== Respuesta de Jira ==="
          echo "$jira_response"

          jira_key=$(echo "$jira_response" | jq -r '.key')
          if [[ -z "$jira_key" || "$jira_key" == "null" ]]; then
            echo "Error: No se pudo crear la tarea en Jira. Revisa los logs."
            exit 1
          fi
          echo "Tarea en Jira creada con éxito. Key: $jira_key"
          echo "jira_key=$jira_key" >> $GITHUB_ENV
