name: Create Sync Issue

on:
  workflow_dispatch: # Este workflow se ejecuta manualmente

jobs:
  create-sync-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Crear Issue de Sincronización
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -d '{
              "title": "Sincronización GitHub-Jira",
              "body": "{\n  \"sync\": {\n    \"jira\": {\n      \"project\": \"CDP\",\n      \"issues\": []\n    }\n  }\n}",
              "labels": ["sync", "jira"]
            }' \
            https://api.github.com/repos/${{ github.repository }}/issues
